module.exports = [
  {
    id: 1,
    name: "Direct Depost",
    amount: 15,
    date: "Jan 1, 2023",
    from: "Employer",
    category: "Income",
  },
  {
    id: 2,
    name: "Direct Depost",
    amount: 5.5,
    date: "Jan 8, 2023",
    from: "Employer",
    category: "Income",
  },
  {
    id: 3,
    name: "Cat Food",
    amount: 12.5,
    date: "Jan 9, 2023",
    from: "Trixies Pet Shop",
    category: "Pets",
  },
  {
    id: 4,
    name: "Direct Depost",
    amount: 5,
    date: "Jan 15, 2023",
    from: "Employer",
    category: "Income",
  },
  {
    id: 5,
    name: "Takeout",
    amount: 23.75,
    date: "Jan 16, 2023",
    from: "Hardee Chinese Food Shop",
    category: "Food",
  },
  {
    id: 6,
    name: "Takeout",
    amount: 23.75,
    date: "Jan 17, 2023",
    from: "Hardee Chinese Food Shop",
    category: "Food",
  },
];
